### ISSUE TITLE
No Releases?

### ISSUE THREAD

**Issue by N0tACyb0rg** [affederaffe/CustomPlatforms#1]
Hey, was just coming to grab it to put into Beat Saber, but there are no releases. Is there a guide on how to compile it, or is there somewhere else to get it? (I'm running v1.15.0)

**Comment by Theenoro** [comment]
https://github.com/affederaffe/CustomPlatforms/actions/runs/833078010

i've used the build from the actions tab.

**Comment by N0tACyb0rg** [comment]
Cool thanks I'll check it out.

**Comment by N0tACyb0rg** [comment]
Yeah it worked I'm closing it.
