### ISSUE TITLE
Chroma incompatibility with Custom Platforms TubeLights

### ISSUE THREAD

**Issue by aggrogahu** [affederaffe/CustomPlatforms#17]
In a recent update to Chroma, apparently the base game LightSwitchEventEffect is destroyed by Chroma and it's replaced with a new Chroma-specific class. This effectively disables any lights in a custom platform that relies on the TubeLights script (SongEventHandler still works though). I believe Aero is aware of this, though I'm not sure if there's any current plans to fix the incompatibility on their end. Perhaps TubeLights script can be updated to be compatible with the Chroma LightSwitchEventEffect.

**Comment by UrkiMimi** [comment]
I had this problem too and I've been waiting for a fix with this issue. I ended up making all of my lights static using "Unused 10" as that lets me color my lights.

**Comment by UrkiMimi** [comment]
I had this issue since 1.18.3

**Comment by UrkiMimi** [comment]
This issue ended up getting fixed in 1.21.0 so it is finally fixed.
