### ISSUE TITLE
Strobe effect on Oculus on game startup

### ISSUE THREAD

**Issue by MetaMemez** [affederaffe/CustomPlatforms#3]
When I load up the game, my screen flashes repeatedly without ever loading in. This only happened when I had custom platforms installed. :/

**Comment by affederaffe** [comment]
Hello, I introduced an issue the last release which resulted in a game breaking black screen.
This is already fixed in later Actions builds (https://github.com/affederaffe/CustomPlatforms/actions), do  you mind trying the latest and see if the bug persists?

**Comment by MetaMemez** [comment]
Sure.

**Comment by MetaMemez** [comment]
Oh yes it's fixed, thank you!
