### ISSUE TITLE
[Feature Request] Register Custom Platforms with Song Core.

### ISSUE THREAD

**Issue by AlexxSeven** [affederaffe/CustomPlatforms#5]
Adding the following line to the "plugin.cs" file should register the mod with song core so that mods can list custom platforms as a suggestion and song core properly detect it.

`SongCore.Collections.RegisterCapability("Custom Platforms");`

IDK how to github properly to do a PR but I've tested it and confirmed it does work.

Without:
![unknown](https://user-images.githubusercontent.com/8524552/122633960-f47b5400-d0a0-11eb-9e67-b4fe1e056ecb.png)

With:
![305340d0fea493eab145e0d1d8547cbc](https://user-images.githubusercontent.com/8524552/122633965-ff35e900-d0a0-11eb-92a5-5c809634c8b2.jpg)

**Comment by affederaffe** [comment]
Thanks for the suggestion, that's a great idea! I'll try to implement it when I have the time.

**Comment by affederaffe** [comment]
Added in the latest release.
