### ISSUE TITLE
judgements and energy bar disappear under the platforms

### ISSUE THREAD

**Issue by tonnentonie** [affederaffe/CustomPlatforms#5]
It may be another mod interfering, I don't know. I know it worked at some point, I am using the latest mod and game version.

**Comment by affederaffe** [comment]
This depends on the Platform you are using, you can try to move those with Counters+

**Comment by tonnentonie** [comment]
I am using the HiWave preset. Is it just not possible to see the energy bar with HiWave?

**Comment by affederaffe** [comment]
Yes, the Platform covers the energy bar so it's not visible.
