### ISSUE TITLE
Game becoming broken after install:

### ISSUE THREAD

**Issue by In4init3** [affederaffe/CustomPlatforms#6]
For some WICKED reason, my game has errors when it's trying to load the mod, without it in the plugins folder, it works fine, but with it, it has some weird SystemIO exceptions.

**Comment by affederaffe** [comment]
Hi, do you mind sending me your log here or on discord (affederaffe#5506)?

**Comment by In4init3** [comment]
its mostly fixed if i have my headset on but without any connections, it has errors also it should be fixed because i can actually launch beat saber and BSIPA after the install
