### ISSUE TITLE
[Feature Request] Toggle for Base Game Tubelight glow

### ISSUE THREAD

**Issue by UrkiMimi** [affederaffe/CustomPlatforms#8]
I am not requesting for the Base Game TubeLight to be added but the lighting system that it uses.

Here's a screenshot if you don't understand

![mockup](https://user-images.githubusercontent.com/74517821/127790147-3e2163a3-9985-4843-bcd5-b42c0d6f55d4.png)

**Comment by FunniFlow** [comment]
Ooh, that's a good idea.

**Comment by MetaMemez** [comment]
This sounds cool

**Comment by UrkiMimi** [comment]
This ended up getting added so I'm gonna close this
