### ISSUE TITLE
UnityProject.zip has no project file.

### ISSUE THREAD

**Issue by FunniFlow** [affederaffe/CustomPlatforms#9]
I can't for the life of me figure out how to use the project, because there's no project file.

**Comment by UrkiMimi** [comment]
[UnityProject.zip](https://github.com/affederaffe/CustomPlatforms/files/6926658/UnityProject.zip) 
Use This.

**Comment by FunniFlow** [comment]
I looked everywhere and there's no project file, only the project contents, so I can't export my platform, and none of the objects in the scenes have attached scripts.
![image](https://user-images.githubusercontent.com/88316465/128126184-83bdf2a6-ee5e-48ee-9c84-486124db8c69.png)

**Comment by affederaffe** [comment]
You have to add the project in the unity hub and open it from there.
